/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arcompression_SubmitListener */

#ifndef _Included_arcompression_SubmitListener
#define _Included_arcompression_SubmitListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arcompression_SubmitListener
 * Method:    compressFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arcompression_SubmitListener_compressFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     arcompression_SubmitListener
 * Method:    decompressFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_arcompression_SubmitListener_decompressFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
